"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { useAuth } from "@/contexts/AuthContext";

export default function RegisterPage() {
  const { registerWithEmail } = useAuth(); const router = useRouter();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [studentId, setStudentId] = useState(""); const [regNo, setRegNo] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const connected = await registerWithEmail({ name, email, password, role: "student", studentId, regNo }); toast.success(connected ? "Account created and PSTU record connected." : "Account created. Confirm your student ID and registration number on the dashboard."); router.push("/dashboard"); } catch (e: any) { toast.error(e?.response?.data?.error || e?.message || "Could not create the account."); } finally { setBusy(false); } };
  return <main className="min-h-[75vh] bg-[#F0FAFC] px-4 py-12"><form onSubmit={submit} className="mx-auto mt-4 max-w-lg rounded-3xl bg-white p-8 shadow-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#087EA4]">PSTU Fisheries</p><h1 className="mt-2 text-3xl font-black text-[#123B4A]">Create your account</h1><p className="mt-2 text-sm text-[#55727D]">Use the ID and registration number listed on your PSTU record to connect your profile.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-semibold sm:col-span-2">Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-semibold">Student ID<input required inputMode="numeric" value={studentId} onChange={(e) => setStudentId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-semibold">Registration No<input required inputMode="numeric" value={regNo} onChange={(e) => setRegNo(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="text-sm font-semibold sm:col-span-2">Password<input type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label></div><button disabled={busy} className="mt-6 w-full rounded-xl bg-[#087EA4] px-5 py-3 font-bold text-white disabled:opacity-60">{busy ? "Creating account…" : "Register"}</button><p className="mt-5 text-center text-sm text-[#55727D]">Already registered? <Link className="font-bold text-[#087EA4]" href="/login">Sign in</Link></p></form></main>;
}
